### ISSUE TITLE
no longer works

### ISSUE THREAD

**Issue by tomchiverton** [dirkjanm/firefox-send-to-xbmc#22]
XBMC puts up a box just after the 'opening stream' progress bat (at 100%) saying 'couldn't locate URL' e.g. for https://www.youtube.com/watch?v=EJCxefsPfmo

**Comment by dirkjanm** [comment]
You most likely have an outdated or broken YouTube plugin on your XBMC. I tested with this url and it works fine. When the URL arrives at XBMC/Kodi and it gives an error there, the issue is probably not related to the Send to XBMC addon, but an XBMC issue. The plugin just sends the url, it is up to XBMC to process it.

**Comment by tomchiverton** [comment]
It's XBMC Gotham (on openelec) with the latest Youttube plugin

**Comment by tomchiverton** [comment]
But does work with XBMC Kodi (v14).
