### ISSUE TITLE
Twitch support

### ISSUE THREAD

**Issue by evaryont** [dirkjanm/firefox-send-to-xbmc#47]
It would be cool to be able to click a button while on Twitch's site to be able to play a given live stream or VOD in Kodi.

A basic button that could be injected in `div.channel-actions`:

``` html
<span class="ember-view">    <a style="background-color: rgb(18, 178, 231);" href="/" target="_blank" class="action js-sub-button subscribe-button button button--purchase">
      <span class="subscribe-text">
        Play on
      </span>
      <span class="subscribe-price button__num-block">
        Kodi
      </span>
    </a>
</span>
```

The background color is Kodi's blue. Screenshot: 
![twitch_play_on_kodi_button_idea](https://cloud.githubusercontent.com/assets/14547/16475297/30bf8fe6-3e32-11e6-95bb-736ab16751e4.png)

**Comment by dirkjanm** [comment]
Twitch support has been added in v3.1. To make it work with twitch channels (live streams) instead of just videos, make sure you have the Kodi Twitch plugin version 2.1.0 or newer (currently in beta) installed. Older versions only support sending recorded videos to Twitch. I'll add the browser button to Twitch when the 2.1 version of Kodi Twitch is out of beta.
